apiVersion: apps/v1
kind: Deployment
metadata:
  name: culqi-deploy
  labels:
    name: culqi-deploy
    app: culqi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: culqi-pod
      app: culqi-app
  template:
    metadata:
      name: culqi-pod
      labels:
        name: culqi-pod
        app: culqi-app
    spec:
      containers:
        - name: culqi-container
          image: "174714178159.dkr.ecr.us-east-1.amazonaws.com/culqi:latest"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          livenessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
