apiVersion: v1
kind: Service
metadata:
  name: culqi-service-np
  labels:
    name: culqi-deploy
    app: culqi-app
spec:
  type: NodePort
  selector:
    app: culqi-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30072
